Issue 사항 해결
dnd-side-project/dnd-9th-5-frontend pull request #48
Opened 2023-09-09 01:24 UTC by guesung

## 💡 왜 PR을 올렸나요?

- 이슈대응
- close #46 

## 💁 무엇이 어떻게 바뀌나요?

1.  Instagram 라우팅
2. CTA 문구 ‘포즈 뽑기’로 변경
3. lottie 재생과 동시에 제시어 바뀜 - 현재는 글자 로드가 좀 느린 것 같음
4. icon → svg로 교체
5. 인스타그램/깃허브 링크 ‘새 창에서 열기’

## 📆 작업 예정인 것이 있나요 ?

-

## 💬 리뷰어분들께

2023-09-09 04:40 UTC, seondal reviewed
이슈해결에 리팩토링까지... 수고하셨습니다아 🥹
리뷰에 이슈만 확인 부탁드려요 !

2023-09-09 04:40 UTC, seondal commented on package.json
> +    "@suspensive/react": "^1.13.0",
오... suspensive는 뭔가용?

2023-09-09 04:40 UTC, seondal commented on src/apis/queries.ts
> +import { useSuspenseInfiniteQuery, useSuspenseQuery } from '@suspensive/react-query';
리팩토링 수고하셨습니다 ㅎㅎ

2023-09-09 04:40 UTC, seondal commented on src/components/Header/CloseButton.tsx
> +    <Link href="/feed" scroll={false}>
엇 이 클로즈 버튼 컴포넌트는 메뉴에서도 쓰이는거라 feed로 고정하면 안되지 않을까요...?!

2023-09-09 04:40 UTC, seondal commented on src/components/Modal/Modal.tsx
<img width="599" alt="스크린샷 2023-09-09 오후 1 29 39" src="https://github.com/dnd-side-project/dnd-9th-5-frontend/assets/75469131/f44cdd7b-bfba-4f8c-9c8e-fbb453493d19">
<img width="573" alt="스크린샷 2023-09-09 오후 1 34 17" src="https://github.com/dnd-side-project/dnd-9th-5-frontend/assets/75469131/d37dd822-f4bc-4c54-bd8c-42a5d6773332">
<img width="558" alt="스크린샷 2023-09-09 오후 1 29 24" src="https://github.com/dnd-side-project/dnd-9th-5-frontend/assets/75469131/fb57dbd8-f428-44cd-8dc2-9cd2aa7dcf09">

본 브랜치에 모달관련 이슈들이 보여서 첨부합니당!

2023-09-09 04:40 UTC, seondal commented on src/components/Modal/PreparingModal.tsx
컴포넌트화 좋네요 ㅎㅎ 생각으로만 하고 있었는데

2023-09-09 11:39 UTC, guesung commented on package.json
> +    "@suspensive/react": "^1.13.0",
[suspensive/react-query](https://tanstack.com/query/v4/docs/react/community/suspensive-react-query)는 따로 isLoading을 표시 하지 않아도 알아서 처리해주는 라이브러리입니다.

[suspensive/react](https://www.npmjs.com/package/@suspensive/react)는 suspensive/react-query를 사용하려면 설치하여야 하는 라이브러리입니다.

2023-09-09 11:41 UTC, guesung commented on src/components/Header/CloseButton.tsx
> +    <Link href="/feed" scroll={false}>
흠 그렇군요 

카카오톡 공유하기로 detail페이지를 타고 들어왔을 때, x버튼을 누르면 이전으로 갈 수가 없어서 feed로 라우팅을 하였습니다.

우선 이 컴포넌트는 router.back()을 default로 하고, detail페이지는 따로 만드는 게 좋겠군요.

2023-09-09 11:47 UTC, guesung commented on src/components/Modal/Modal.tsx
공통 컴포넌트 Modal을 수정하고, 다른 쪽을 확인을 못했네요 .. 확인 감사합니다

수정했습니다 ! 👍 👍

2023-09-09 18:53 UTC, seondal commented on src/components/Header/CloseButton.tsx
> +    <Link href="/feed" scroll={false}>
오 detail로 타고 들어왔을 때를 생각 못했네요...!
속성으로 목적지를 받는게 더 좋을 것 같아요 !!

2023-09-09 20:56 UTC, seondal requested changes
<img width="1160" alt="스크린샷 2023-09-10 오전 5 52 35" src="https://github.com/dnd-side-project/dnd-9th-5-frontend/assets/75469131/f36416d3-904d-45c3-a505-d7b7c2d1a79f">

위와 같은 이슈가 상세페이지와 메인페이지에서 생기고 있는데 참고 부탁드립니답....!

나름대로 디버깅 해봤더니 헤더의 z-10 속성이 className으로는 들어가있지만 스타일로 적용이 안되어 있더라구요! (아래 사진 참고)
본 브랜치에서 tailwindCSS 설정? 단위? 를 바꾼게 원인 아닐까 하는 추리해봅니다.... 흠.. 🧐
~근데.. 추리는 했는데.... 능력 부족으로.. 고치는건 실패 했어요...... 8ㅁ8~

<img width="1378" alt="스크린샷 2023-09-10 오전 5 52 09" src="https://github.com/dnd-side-project/dnd-9th-5-frontend/assets/75469131/78560fce-ff70-4b0d-8422-c4e3aaefde68">

<img width="628" alt="스크린샷 2023-09-10 오전 5 53 10" src="https://github.com/dnd-side-project/dnd-9th-5-frontend/assets/75469131/42e18e5d-f956-4a9f-ba29-4f1e307065a5">

2023-09-09 20:57 UTC, seondal commented on package.json
> +    "@suspensive/react": "^1.13.0",
오호 감사합니다

2023-09-09 21:07 UTC, seondal approved these changes
21cab444046142e754b68a4b78f5c46bebde2cee

2023-09-09 21:23 UTC, seondal requested changes
http://localhost:3000/detail/36

이미지 상세보기 눌러서 이미지 모달 열었을 때 세로가 좀 긴 이미지는 세로길이가 작은 화면에서 잘리는 현상이 발생합니당..! 스크롤을 넣거나 이미지 높이가 화면 크기를 넘지 않게 조정해야할 것 같아요

<img width="538" alt="스크린샷 2023-09-10 오전 6 21 43" src="https://github.com/dnd-side-project/dnd-9th-5-frontend/assets/75469131/797071cd-1496-404f-8f4a-d9d370f49262">

2023-09-09 21:39 UTC, seondal approved these changes
0b1c57cc158df3949d3373f0b16d2db29cc32571

2023-09-10 00:38 UTC, guesung commented
저도 z-index이슈 찾긴했는데 원인을 찾지 못했는데 해결하셧군요 ..! 최곱니당 👍 👍

2023-09-10 00:40 UTC, merged