Feature: JSON-LD 추가
dnd-side-project/dnd-9th-5-frontend pull request #76
Opened 2024-08-08 06:21 UTC by guesung

## What is this PR? :mag:

- JSON LD 추가

## Changes :memo:

JSON-LD는 구조화된 데이터를 크롤링 봇에 제공해줌으로써, 검색 엔진에 더 구조화되어 노출되도록 해주는 방식입니다.

### AS-IS
     
<img width="657" alt="image" src="https://github.com/user-attachments/assets/01b5ac9e-4cb4-4c6b-971a-edb8876851a3">

### TO-BE (예시)
<img width="581" alt="image" src="https://github.com/user-attachments/assets/a1d1530f-3fd3-49e5-bdb8-f7292bb38345">

2024-08-10 16:33 UTC, seondal requested changes

2024-08-10 16:33 UTC, seondal commented on src/components/JsonLD/JsonLD.tsx
layout.tsx에서만 사용되는 컴포넌트인만큼,, 따로 빼서 컴포넌트 폴더를 늘리는 것 보다 한 파일 내에서 선언하면 좋을 것 같습니다..!

2024-08-12 05:07 UTC, guesung commented on src/app/layout.tsx
>                <OverlayProvider>{children}</OverlayProvider>
React Suspense는 주로 비동기 작업(데이터 패칭, 지연 로딩 컴포넌트)을 처리하기 위해 사용합니다. JSON-LD스크립트는 정적 메타 데이터로, 비동기 로딩이 필요하지 않습니다. 

또한, Suspense로 감싸면 서버에서 렌더링을 하지 않기 때문에 내부 컴포넌트의 렌더링에 있어서 지연이 발생해 SEO에 부정적인 영향을 미칠 수 있습니다.

2024-08-12 05:09 UTC, guesung commented on src/components/JsonLD/JsonLD.tsx
`layout.tsx`파일 하나에 전부 넣으면 코드의 가독성을 해치지 않을까 해서 분리를했습니다. 예들 들어 현재 layout.tsx에 있는 Analytics처럼요. QueryProvider와 RecoilProvider는 RCC라 분리가 불가피한 컾모넌트라고 생각합니다.

정리하면, 가독성을 위해 컴포넌트는 분리하는 것이 좋다고 생각하며 저희가 최근에 구두로 정한 컴포넌트 구조 컨벤션처럼, layout.tsx에서 사용하는 컴포넌트는 layout.tsx와 동일한 depth에 작성하는 방안을 제안합니다.

2024-08-12 05:15 UTC, guesung commented
추가로, GA컴포넌트인 Analytics를 둘러싼 Suspense를 제거했습니다. Analytics컴포넌트 내부에서 Script 속성에 `strategy="afterInteractive"`가 추가가 되어 이미 Next.js에서 Hydration이후 해당 스크립트를 실행합니다. [공식문서](https://nextjs.org/docs/pages/building-your-application/optimizing/scripts#strategy)


9e319a618bf1685c0f942dd66bd72affdcd79264

2024-08-12 07:22 UTC, seondal commented on src/components/JsonLD/JsonLD.tsx
제안해주신 방안으로 진행하면 좋을 것 같습니다!!

2024-08-12 07:29 UTC, seondal commented on src/components/JsonLD/JsonLD.tsx
[a478e44](https://github.com/dnd-side-project/dnd-9th-5-frontend/pull/76/commits/a478e448c269df20211d0a393d01a150c09957c5)

2024-08-12 07:29 UTC, seondal approved these changes

2024-08-13 03:41 UTC, merged