Refactor: 회원가입 로직 리팩토링
dnd-side-project/dnd-9th-5-frontend pull request #77
Opened 2024-08-08 16:25 UTC by guesung

## What is this PR? :mag:

## Changes :memo:

## Screenshot :camera:

2024-08-10 16:38 UTC, seondal requested changes
친절하게 PR에 설명 남겨주셔서 감사합니다. 많이 배워갑니다..!
폴더구조 관련해서 코멘트 남긴 부분 확인 부탁드려요 :)

2024-08-10 16:38 UTC, seondal commented on src/app/auth/logout/page.tsx
한가지 컴포넌트로 이루어진 페이지를 만드는 이유를 잘 모르겠습니다..!
가능하면 파일 갯수를 줄이고 싶은데, 본 페이지에 LogoutComponent 코드를 넣는건 어려울까요?

2024-08-12 04:34 UTC, guesung commented on src/app/auth/logout/page.tsx
컨벤션을 맞추기 위해서 따로 뺐습니다.

모든 페이지는 RSC(React Server Component)로 두고, 그 하위에 RSC와 RCC(React Client Component)로 구분해야 추후 확장에 있어서 RSC와 RCC를 구분하여 컴포넌트를 추가할 수 있기 때문입니다.

만약 이 page.tsx 컴포넌트가 RCC이면, 추후 RSC로 구현이 가능한 컴포넌트가 추가되었을 때 구조를 다시 바꿔야 한다는 불편함이 예상됩니다. 그래서 모든 page.tsx컴포넌트는 RSC로 두고, 하위 컴포넌트에서 RSC와 RCC를 구분하고자 하는 컨벤션을 사용하는 건 어떨까요?

의견 자유롭게 제시해주세요 !!

2024-08-12 04:54 UTC, seondal commented on src/app/auth/logout/page.tsx
모든 페이지를 RSC로 두는 것에 대해서는 찬성합니다..!

폴더구조에 대해서, page.tsx도 하나의 컴포넌트인 만큼 해당 페이지에 종속되는 컴포넌트들은 같은 폴더 내에 (components 폴더를 매번 따로 만들지 않고) 정의하는 방식으로 폴더의 depth를 줄여나가면 더 좋을 것 같습니다!

2024-08-12 04:54 UTC, guesung commented on src/app/auth/logout/page.tsx
<img width="863" alt="image" src="https://github.com/user-attachments/assets/e3502356-bf27-4d94-9667-3827701d0ea4">

좋습니다 :) 구두로 논의한 방식으로 컨벤션에 추가했습니다 !

2024-08-12 04:56 UTC, guesung commented on src/app/auth/logout/page.tsx
7d2acb30a30427e744cc7ada8a718fae940cbfb5 수정한 커밋입니다 !

2024-08-12 05:54 UTC, seondal commented on src/app/auth/logout/page.tsx
[557e50a](https://github.com/dnd-side-project/dnd-9th-5-frontend/pull/77/commits/557e50af0e134aa499f10c0c6defb6b4a539a868) 추가된 컨벤션에 맞춰서 리팩토링 진행했습니다!

2024-08-12 06:21 UTC, guesung commented
@seondal 머지할까요 ??

2024-08-12 06:26 UTC, seondal approved these changes

2024-08-12 07:03 UTC, merged