Refactor: 사용자 정보를 쿠키에서 관리한다
dnd-side-project/dnd-9th-5-frontend pull request #78
Opened 2024-08-09 03:40 UTC by guesung

## What is this PR? :mag:

## Changes :memo:

## Screenshot :camera:

2024-08-10 16:44 UTC, seondal requested changes
프론트엔드 단에서 쿠키를 사용하는 법에 대해 알 수 있었네요 감사합니다 ㅎㅎ

2024-08-10 16:44 UTC, seondal commented on src/apis/config/privateApi.ts
> +    location.href = '/';
이미 로그인은 완료되고 세션이 만료된 상태에서 리다이렉트를 했을 때 로그인처리를 위해 auth/logout으로 이동되게 해놓았던 부분인데, 혹시 세션 만료까지 테스트 완료된 코드일까요?!

2024-08-12 04:38 UTC, guesung commented on src/components/Login/LogoutModal.tsx
> +
로그아웃 처리

2024-08-12 04:39 UTC, guesung commented on src/apis/config/privateApi.ts
> +    location.href = '/';
네, 로그아웃을 할 경우, [LogoutModal](https://github.com/dnd-side-project/dnd-9th-5-frontend/pull/78/files#r1713162846)에서 쿠키에서 토큰을 제거하고, 메인 페이지로 이동합니다. 테스트 완료했습니다 !

토큰 제거를 위해 auth/logout페이지로 굳이 이동할 필요가 없다고 생각하여 해당 페이지를 제거했습니다. 혹시 다른 의견 있으시면 편하게 말씀해주세요 !

2024-08-12 06:01 UTC, seondal commented on src/apis/config/privateApi.ts
> +    location.href = '/';
요 부분이 사용자가 로그아웃을 하는 부분이 아닌 세션 만료를 포함한 로그인 오류에 대해 처리하는 부분입니답..!
오류가 발생했을 때 토큰 제거가 진행되는지 알고싶습니당!

2024-08-12 06:27 UTC, guesung commented on src/apis/config/privateApi.ts
> +    location.href = '/';
넵, ` if (status === ERROR_UNAUTHORIZED) {`로직은 그대로 동일하게 적용되어 있어서 오류 발생 시 토큰 제거하게 됩니다 !

```
// src/constants/error.ts
export const ERROR_UNAUTHORIZED = 401; 
```

2024-08-12 07:03 UTC, merged