Feature: instgram 딥링크 구현
dnd-side-project/dnd-9th-5-frontend pull request #81
Opened 2024-08-09 06:04 UTC by guesung

## What is this PR? :mag:

- instgram 딥링크를 구현하였습니다.

## Changes :memo:

기존, 아래 AS-IS의 영상처럼 그냥 instagram link로 연결 시 에러가 발생했습니다.

URI Scheme라는 딥링크 기법을 사용하여, 딥링크를 구현하였습니다.

ref : [Android, iOS 웹뷰에서 딥링크 열기 ](https://www.tosspayments.com/blog/articles/dev-4?utm_source=tossbusiness&utm_medium=blog&utm_campaign=dev-10)

## Screenshot :camera:

### AS-IS

- instagram 앱 설치 시

https://github.com/user-attachments/assets/2967b6d6-ec6d-4160-868f-3c6f27810c8b

- instagram 앱 미설치 시

https://github.com/user-attachments/assets/2d638ca8-ae0c-4d82-96d3-08c7e16ce84a

### TO-BE
- instagram 앱 설치 시

https://github.com/user-attachments/assets/0bec6a75-5f4f-4733-a8dd-212c3f37d106

- instagram 앱 미설치 시

https://github.com/user-attachments/assets/a25eaf50-7780-45a9-b426-43884a2f6a2c

2024-08-10 16:50 UTC, seondal requested changes
DeepLink 기능이 이렇게 따로 있는지 몰랐네요! 좋은 기능 알려주셔서 감사합니다 :)
리뷰한 부분 한번 확인해주시면 감사하겠습니다

2024-08-10 16:50 UTC, seondal commented on src/hooks/useLaunchApp.ts
> +      alert('Instagram 앱이 설치되지 않았습니다. 앱을 먼저 설치해주세요.');
앱이 설치되지 않은 경우에는 웹으로 해당 페이지를 새로 여는 형식으로 넘어갈 수 있게 변경해주시면 감사하겠습니다..!

2024-08-10 16:50 UTC, seondal commented on src/utils/isAndroid.ts
개인적으로 이 아래는 비슷한 기능을 하고 있는 컴포넌트들인 만큼 한 파일 내에 정의하거나 getOSByUserAgent.ts 내에 정의하면 더 좋을 것 같은데 어떻게 생각하시나요..? 개인의 선호도 차이인데,, 개인적으로 저는 유지보수 측면에서 중복으로 사용되지 않고 + 비슷한 기능을 하는 컴포넌트들은 한 페이지 내에 정의되는걸 선호합니다...!!

2024-08-11 02:23 UTC, guesung commented on src/hooks/useLaunchApp.ts
> +      alert('Instagram 앱이 설치되지 않았습니다. 앱을 먼저 설치해주세요.');
Instagram 앱이 설치되지 않은 경우, 웹으로 이동하려 할 때 이동되지 않고 오류가 발생했습니다. Instagram에서 외부 웹앱으로의 이동을 금지한 것 같습니다.

제 기기에서만 발생하는 문제일 수 있으니, 가능하시다면 테스트 한 번 부탁드립니다! 현재 Posepicker에서는 instagram 웹으로 이동 중이어서, Instagram 앱을 삭제한 후 테스트가 가능할 것 같습니다.

2024-08-11 02:26 UTC, guesung commented on src/utils/isAndroid.ts
그렇군요. 저도 이 파일을 작성하면서 이렇게 각 함수를 분리하는 게 맞는 지 의문이 들었어요. 좋은 지적 감사합니다 ☺️

저희 기존 유틸 함수 방식을 참고햇을 때, cookieController처럼 하나의 파일에서 관련된 유틸 함수를 export하고 있으니 이 방식을 유지해서 이 파일들 또한 하나로 합치면 좋을 거 같습니다. 이 또한 [노션 - 컨벤션](https://www.notion.so/shineshine/31ee8adffafa4297820ed656e7244103?pvs=4)에 추가하겠습니다.

2024-08-12 04:25 UTC, seondal commented on src/hooks/useLaunchApp.ts
> +      alert('Instagram 앱이 설치되지 않았습니다. 앱을 먼저 설치해주세요.');
인스타그램이 설치되지 않은 케이스는 pc 웹으로 테스트를 했었는데 pc에서는 정상 작동이 되었던 것 같습니다..!
인스타그램이 설치되지 않은 모바일 기기를 제가 구하지 못해서 확인이 어렵네요 ㅠㅠ

2024-08-12 04:27 UTC, guesung commented on src/hooks/useLaunchApp.ts
> +      alert('Instagram 앱이 설치되지 않았습니다. 앱을 먼저 설치해주세요.');
앗, PC를 고려하지 못했네요. 

PC인 지 체크해서, PC라면 instagram웹으로 이동하도록 분기처리 추가하겠습니다.

2024-08-12 04:46 UTC, guesung commented on src/hooks/useLaunchApp.ts
> +      alert('Instagram 앱이 설치되지 않았습니다. 앱을 먼저 설치해주세요.');
로컬이 아니라 배포된 posepicker에서 확인을 해보니 instagram이 삭제되어 있어도 잘 이동하는 군요.

그렇다면, 문제 상황은 `instagram이 설치되었을 때 instagram앱 이동 후 기존 posepicker웹으로 돌아왔을 때 흰화면이 뜬다`로 정의할 수 있을 거 같습니다.

결론적으로, 모바일의 경우 딥링크로 먼저 이동 후, 이동이 안된다면(앱이 설치되어 있지 않다면) 앱으로 이동하도록 수정하겠습니다.

2024-08-12 04:59 UTC, guesung commented on src/hooks/useLaunchApp.ts
> +      alert('Instagram 앱이 설치되지 않았습니다. 앱을 먼저 설치해주세요.');
기기 : iPhone13, 배포환경입니다. instagram을 설치하지 않고 instagram링크를 클릭할 경우 아래 영상과 같은 에러가 발생했습니다. 

좀 전에 첫 실행은 되는 거 같더니, 다시 해보니 아래 영상처럼 안되더라구요. 전에 ipad에서 정상실행되셨다고 하셨는데, 혹시 한 번 더 테스트 해보실 수 있을까요 ??

https://github.com/user-attachments/assets/d77204ab-caa2-4e19-9bad-65f452f1105c

2024-08-12 06:03 UTC, seondal commented on src/hooks/useLaunchApp.ts
> +      alert('Instagram 앱이 설치되지 않았습니다. 앱을 먼저 설치해주세요.');
https://github.com/user-attachments/assets/ad8bc954-cb03-46b4-b32d-36ffe8b423ea

인스타그램 앱이 설치되지 않은 ipad입니다!

2024-08-12 06:18 UTC, seondal commented on src/utils/isAndroid.ts
@guesung 넵! 요부분 반영하구 머지해주세요!

2024-08-12 06:41 UTC, guesung commented on src/utils/isAndroid.ts
b573fcbb3884d1e5e562745a1f1ddff8e1eaab43

2024-08-12 06:48 UTC, guesung commented on src/hooks/useLaunchApp.ts
> +      alert('Instagram 앱이 설치되지 않았습니다. 앱을 먼저 설치해주세요.');
그렇군요. 선영님 아이패드에 instagram 로그인이 안되어있는 걸로보아, 로그인의 유무 차이는 아니고 ,, 버전 혹은 기기 별로 차이가 있는 듯합니다.

instagram을 설치하지 않고 휴대폰으로 접속하니 instagram 설치 페이지로 이동을 시키는 것을 확인했습니다. 휴대폰으로 접속했고 && instagram이 설치가 되지 않았다면 해당 페이지로 저희도 접속시키면 어떨까요?

해당 페이지입니다. https://www.instagram.com/?ig_mid=CD9B4D49-EC8F-480D-B95E-34CBCD5F019D&utm_source=igweb&fall_back_to_web=false&launch_app_store=true

2024-08-12 06:53 UTC, guesung commented on src/hooks/useLaunchApp.ts
> +      alert('Instagram 앱이 설치되지 않았습니다. 앱을 먼저 설치해주세요.');
저도 다시 해보니 되는 군요. 원인이 로그인 유무가 아닌 듯하고,, 조금 더 테스트가 필요해보입니다.

우선, 정확한 원인이 파악되기 전까지 우선 웹사이트 링크로 이동하고, 여러가지 테스트를 해본 후 이슈를 해결하거나 조건부 처리를 통해 해결을 하면 좋을 듯합니다.

2024-08-12 06:54 UTC, guesung commented on src/hooks/useLaunchApp.ts
> +      alert('Instagram 앱이 설치되지 않았습니다. 앱을 먼저 설치해주세요.');
960be31d09c8704f98210d946c896ad84aeab917

2024-08-12 07:02 UTC, seondal commented on src/hooks/useLaunchApp.ts
> +      alert('Instagram 앱이 설치되지 않았습니다. 앱을 먼저 설치해주세요.');
감사합니당!

2024-08-12 07:02 UTC, seondal approved these changes

2024-08-12 07:04 UTC, merged